#define APP_VERSION_MAJOR "0"
#define APP_VERSION_MINOR "1"
#define APP_VERSION_PATCH "0"
#define APP_VERSION_BUILD "658ad75"
#define APP_VERSION_DATE  "Mon Sep 18 07:21:14 +07 2017"
#define APP_ROOT          "/home/bailey/Developer/work/factorii"
