branches:
    only:
        - ci
        - master
skip_tags: true
environment:
    BUILD_REVISION: git-ci
    BUILD_TIMESTAMP: now
    CFLAGS: /WX
    matrix:
        - BUILD_SHARED_LIBS: OFF
        # - BUILD_SHARED_LIBS: ON
matrix:
    fast_finish: true

build_script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS% ..
    - cmake --build .
